Write-Output " "
Write-Output "🏃 FULL PC SETUP STARTING..."
Write-Output " "

& "$PSScriptRoot\winget\setup.ps1"
Write-Output " "
& "$PSScriptRoot\fonts\setup.ps1"
Write-Output " "
& "$PSScriptRoot\windows-terminal\setup.ps1"
Write-Output " "
& "$PSScriptRoot\powershell\setup.ps1"
Write-Output " "
& "$PSScriptRoot\oh-my-posh\setup.ps1"
Write-Output " "
& "$PSScriptRoot\configuration\setup.ps1"

Write-Output " "
Write-Output "✅ FULL PC SETUP COMPLETED SUCCESSFULLY!"
Write-Output " "