name: Windows setup test

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      
    - name: Run setup script
      shell: PowerShell
      run: iwr -useb https://raw.githubusercontent.com/roquec/scripts/main/windows/bootstrap.ps1 | iex

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify
      run: Get-InstalledModule

    - name: Verify
      shell: PowerShell
      run: pwsh -NoProfile -File .\.github\actions\verify.ps1