name: Windows setup tests

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      
    - name: Execute script
      shell: pwsh
      run: iwr -useb https://raw.githubusercontent.com/roquec/scripts/main/windows/bootstrap.ps1 | iex

    - uses: actions/checkout@v4

    - name: Verify Installation
      shell: pwsh
      run: .\.github\actions\verify-installation.ps1
      
    - name: Verify Terminal Config
      shell: pwsh
      run: .\.github\actions\verify-terminal-config.ps1

