name: Test Windows setup script

on: [push]  # Trigger the workflow on push events to any branch. You can customize this.

jobs:
  run-bat:
    runs-on: windows-latest  # Use the latest Windows runner available on GitHub Actions

    steps:
    - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Execute BAT file
      run: |
        .\windows\setup.ps1
